server:
  port: 8081

spring:
  application:
    name: board_vue_back

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_board?createDatabaseIfNotExist=true
    username: root
    password: 11111111